### ISSUE TITLE
Request to bump OCaml version to >= 4.07.0

### ISSUE THREAD

**Issue by pi8027** [math-comp/docker-mathcomp#12]
IIUC, the image `mathcomp/mathcomp:1.12.0-coq-8.14` seems to use OCaml 4.05.0, but the only released version of Coq-elpi compatible with Coq 8.14 (coq-elpi.1.11.2) requires OCaml to be 4.07.0 or later. These constraints make it [unable to use Coq-elpi in this image](https://github.com/math-comp/algebra-tactics/runs/3994689207?check_suite_focus=true).

**Comment by gares** [comment]
Hello @erikmd , I did debug the problem and it is unfixable on the coq-elpi side since stdlib-shims is "incomplete" on 4.05.
At the same time the Coq-Platform for 8.13 is based on 4.07, while the one for 8.14 is based on 4.10, IIRC.
Ditching 4.05 seems not a big deal to, and 4.07 is a pretty solid release.

**Comment by erikmd** [comment]
Hi @gares, thanks for your feedback;
actually I believe my earlier comment was not clear enough:
in the current version of all stable Docker images `mathcomp/mathcomp:*`, ocaml 4.07 was already available,
albeit not the default switch (which admittedly was making the use of these images cumbersome:
e.g., when using the docker-coq-action, one would need to override the [`before_install`](https://github.com/coq-community/docker-coq-action#before_install) field)

Anyway, the plan was clearly to remove 4.05 when fully addressing https://github.com/coq-community/docker-coq/issues/30
and ensuring that *all* Docker-Coq images are mono-switch.

But in the meantime, it looks very sensible to me to do a first update of Docker-MathComp by only keeping 4.07 from now on.

So I gonna merge PR https://github.com/math-comp/docker-mathcomp/pull/14 now to this aim and rebuild all Docker-MathComp images, so that we'll directly get a more recent ocaml this Friday by default (namely, 4.07 (and let me know if there's some specific need regarding 4.10 as well from your side)).

**Comment by erikmd** [comment]
> So I gonna merge PR #14 now to this aim and rebuild all Docker-MathComp images

Just FTR, one can follow the now on-going build in this GitLab CI pipeline:

https://gitlab.com/math-comp/docker-mathcomp/-/pipelines/421497895

**Comment by pi8027** [comment]
It seems to me that this issue has been addressed (although images are not mono-switch yet?). Thanks, @erikmd.

**Comment by erikmd** [comment]
Thanks @pi8027! you're right:
- we can close this issue, indeed solved for docker-mathcomp images that are now mono-switch "after-the-fact".
- the mono-switch refactoring of docker-coq is still pending though; will look after that as soon as I can.
