### ISSUE TITLE
Block update of librairies

### ISSUE THREAD

**Issue by thery** [math-comp/docker-mathcomp#4]
It seems that the docker image ``mathcomp:1.7.0-coq-8.9`` allows the update of the librairies, 
this may be a good idea to disable this.

https://travis-ci.org/thery/grobner/builds/542340957#L582-L592

**Comment by CohenCyril** [comment]
@erikmd I took a look at the Dockerfile and I do not understand how this is possible, since mathcomp is pinned...

**Comment by CohenCyril** [comment]
Actually I think I did not understand the semantics of pin... apparently a pin does not forbid uninstall, and since grobner does not need `coq-mathcomp-character` and only this one was pinned, it uninstalls it and reinstall whatever version of mathcomp is required... Thus, I guess the Dockerfile should pin `coq-mathcomp-ssreflect` instead.

**Comment by erikmd** [comment]
Thanks @thery for your report !
@CohenCyril, indeed there is probably some opam gotcha here, so we could pin ssreflect rather than character.
Or maybe it'd be even better to pin all mathcomp packages, a bit like these installation instructions ?
https://github.com/math-comp/math-comp/blob/master/INSTALL.md#compilation-and-installation-of-a-custom-version-using-opam
But I don't know what would be optimal here - and I am currently away from my (PC) keyboard so I can't test this right away...
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by erikmd** [comment]
Hi @thery @CohenCyril,
I did more experiments with OPAM 2.0.5 and I confirm that just pinning `coq-mathcomp-character` (as it is the case now) implies `opam install coq-mathcomp-SOMELIB` will fail only if `SOMELIB = character` or `SOMELIB depends on character`, but proposes to reinstall everything if:

1. `SOMELIB = ssreflect,fingroup,algebra,solvable, or field` (`character deps. on SOMELIB`)
2. or `SOMELIB depends on ssreflect,fingroup,algebra,solvable, or field`

Both issues are solved when pinning all mathcomp packages or just `coq-mathcomp-ssreflect`…
but on second thought it might occur some day that the opam-coq-archive contains a given release of `coq-mathcomp-ssreflect`, compatible with *several* versions of `coq-mathcomp-fingroup` (for example). In this case, there would be an issue, which can be avoided by pinning `coq-mathcomp-fingroup` from now on as well (a bit like it is done for `mathcomp/mathcomp-dev` [(source)](https://github.com/math-comp/math-comp/blob/a03e0cb0ff40afabcaccba7f764076355ca82962/Dockerfile#L25-L30), albeit in this case the pinning was necessary for another reason, namely the kind of the pinning being `-k path`).

So I'm going to update the `mathcomp/mathcomp` images by pinning the 6 packages at once.

**Comment by erikmd** [comment]
Closing as implemented by 22e6a8d6a923fae514a291538aac9b33c102718f in `master` and [propagated](https://github.com/erikmd/docker-hub-helper#add-a-commit-in-master-and-rebase-all-stable-branches) to other branches to trigger the builds on [Docker Hub](https://cloud.docker.com/u/mathcomp/repository/docker/mathcomp/mathcomp/timeline).
